---
- hosts: all
  become: true

  tasks:
    - name: Install Prometheus NodeExporter
      apt:
        install: prometheus-node-exporter
          when: ansible_pkg_mgr == 'apt'  # Optional: ensures it's only run on Debian/Ubuntu systems
